/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperatorProfileRouteImport } from './routes/_authenticated.operator.profile'
import { Route as AuthenticatedOperatorNotificationsRouteImport } from './routes/_authenticated.operator.notifications'
import { Route as AuthenticatedOperatorDashboardRouteImport } from './routes/_authenticated.operator.dashboard'
import { Route as AuthenticatedOperatorBenefitsRouteImport } from './routes/_authenticated.operator.benefits'
import { Route as AuthenticatedInsuranceRejectedRouteImport } from './routes/_authenticated.insurance.rejected'
import { Route as AuthenticatedInsuranceProfileRouteImport } from './routes/_authenticated.insurance.profile'
import { Route as AuthenticatedInsurancePendingRouteImport } from './routes/_authenticated.insurance.pending'
import { Route as AuthenticatedInsuranceNotificationsRouteImport } from './routes/_authenticated.insurance.notifications'
import { Route as AuthenticatedInsuranceDashboardRouteImport } from './routes/_authenticated.insurance.dashboard'
import { Route as AuthenticatedInsuranceApprovedRouteImport } from './routes/_authenticated.insurance.approved'
import { Route as AuthenticatedCustomerRequestsRouteImport } from './routes/_authenticated.customer.requests'
import { Route as AuthenticatedCustomerProfileRouteImport } from './routes/_authenticated.customer.profile'
import { Route as AuthenticatedCustomerNotificationsRouteImport } from './routes/_authenticated.customer.notifications'
import { Route as AuthenticatedCustomerLoyaltyRouteImport } from './routes/_authenticated.customer.loyalty'
import { Route as AuthenticatedCustomerDashboardRouteImport } from './routes/_authenticated.customer.dashboard'
import { Route as AuthenticatedCustomerBenefitsRouteImport } from './routes/_authenticated.customer.benefits'
import { Route as AuthenticatedCustomerAssignmentsRouteImport } from './routes/_authenticated.customer.assignments'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated.admin.notifications'
import { Route as AuthenticatedAdminLoyaltyRouteImport } from './routes/_authenticated.admin.loyalty'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminBenefitsRouteImport } from './routes/_authenticated.admin.benefits'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated.admin.assignments'
import { Route as AuthenticatedCustomerOperatorsIndexRouteImport } from './routes/_authenticated.customer.operators.index'
import { Route as AuthenticatedCustomerMachinesIndexRouteImport } from './routes/_authenticated.customer.machines.index'
import { Route as AuthenticatedAdminServiceRequestsIndexRouteImport } from './routes/_authenticated.admin.service-requests.index'
import { Route as AuthenticatedAdminOperatorsIndexRouteImport } from './routes/_authenticated.admin.operators.index'
import { Route as AuthenticatedAdminMachinesIndexRouteImport } from './routes/_authenticated.admin.machines.index'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated.admin.customers.index'
import { Route as AuthenticatedCustomerOperatorsIdRouteImport } from './routes/_authenticated.customer.operators.$id'
import { Route as AuthenticatedCustomerMachinesIdRouteImport } from './routes/_authenticated.customer.machines.$id'
import { Route as AuthenticatedAdminServiceRequestsIdRouteImport } from './routes/_authenticated.admin.service-requests.$id'
import { Route as AuthenticatedAdminOperatorsIdRouteImport } from './routes/_authenticated.admin.operators.$id'
import { Route as AuthenticatedAdminMachinesIdRouteImport } from './routes/_authenticated.admin.machines.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated.admin.customers.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperatorProfileRoute =
  AuthenticatedOperatorProfileRouteImport.update({
    id: '/operator/profile',
    path: '/operator/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperatorNotificationsRoute =
  AuthenticatedOperatorNotificationsRouteImport.update({
    id: '/operator/notifications',
    path: '/operator/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperatorDashboardRoute =
  AuthenticatedOperatorDashboardRouteImport.update({
    id: '/operator/dashboard',
    path: '/operator/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperatorBenefitsRoute =
  AuthenticatedOperatorBenefitsRouteImport.update({
    id: '/operator/benefits',
    path: '/operator/benefits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsuranceRejectedRoute =
  AuthenticatedInsuranceRejectedRouteImport.update({
    id: '/insurance/rejected',
    path: '/insurance/rejected',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsuranceProfileRoute =
  AuthenticatedInsuranceProfileRouteImport.update({
    id: '/insurance/profile',
    path: '/insurance/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsurancePendingRoute =
  AuthenticatedInsurancePendingRouteImport.update({
    id: '/insurance/pending',
    path: '/insurance/pending',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsuranceNotificationsRoute =
  AuthenticatedInsuranceNotificationsRouteImport.update({
    id: '/insurance/notifications',
    path: '/insurance/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsuranceDashboardRoute =
  AuthenticatedInsuranceDashboardRouteImport.update({
    id: '/insurance/dashboard',
    path: '/insurance/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsuranceApprovedRoute =
  AuthenticatedInsuranceApprovedRouteImport.update({
    id: '/insurance/approved',
    path: '/insurance/approved',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerRequestsRoute =
  AuthenticatedCustomerRequestsRouteImport.update({
    id: '/customer/requests',
    path: '/customer/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerProfileRoute =
  AuthenticatedCustomerProfileRouteImport.update({
    id: '/customer/profile',
    path: '/customer/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerNotificationsRoute =
  AuthenticatedCustomerNotificationsRouteImport.update({
    id: '/customer/notifications',
    path: '/customer/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerLoyaltyRoute =
  AuthenticatedCustomerLoyaltyRouteImport.update({
    id: '/customer/loyalty',
    path: '/customer/loyalty',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerDashboardRoute =
  AuthenticatedCustomerDashboardRouteImport.update({
    id: '/customer/dashboard',
    path: '/customer/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerBenefitsRoute =
  AuthenticatedCustomerBenefitsRouteImport.update({
    id: '/customer/benefits',
    path: '/customer/benefits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerAssignmentsRoute =
  AuthenticatedCustomerAssignmentsRouteImport.update({
    id: '/customer/assignments',
    path: '/customer/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLoyaltyRoute =
  AuthenticatedAdminLoyaltyRouteImport.update({
    id: '/admin/loyalty',
    path: '/admin/loyalty',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBenefitsRoute =
  AuthenticatedAdminBenefitsRouteImport.update({
    id: '/admin/benefits',
    path: '/admin/benefits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/admin/assignments',
    path: '/admin/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerOperatorsIndexRoute =
  AuthenticatedCustomerOperatorsIndexRouteImport.update({
    id: '/customer/operators/',
    path: '/customer/operators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerMachinesIndexRoute =
  AuthenticatedCustomerMachinesIndexRouteImport.update({
    id: '/customer/machines/',
    path: '/customer/machines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminServiceRequestsIndexRoute =
  AuthenticatedAdminServiceRequestsIndexRouteImport.update({
    id: '/admin/service-requests/',
    path: '/admin/service-requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOperatorsIndexRoute =
  AuthenticatedAdminOperatorsIndexRouteImport.update({
    id: '/admin/operators/',
    path: '/admin/operators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMachinesIndexRoute =
  AuthenticatedAdminMachinesIndexRouteImport.update({
    id: '/admin/machines/',
    path: '/admin/machines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/admin/customers/',
    path: '/admin/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerOperatorsIdRoute =
  AuthenticatedCustomerOperatorsIdRouteImport.update({
    id: '/customer/operators/$id',
    path: '/customer/operators/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomerMachinesIdRoute =
  AuthenticatedCustomerMachinesIdRouteImport.update({
    id: '/customer/machines/$id',
    path: '/customer/machines/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminServiceRequestsIdRoute =
  AuthenticatedAdminServiceRequestsIdRouteImport.update({
    id: '/admin/service-requests/$id',
    path: '/admin/service-requests/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOperatorsIdRoute =
  AuthenticatedAdminOperatorsIdRouteImport.update({
    id: '/admin/operators/$id',
    path: '/admin/operators/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMachinesIdRoute =
  AuthenticatedAdminMachinesIdRouteImport.update({
    id: '/admin/machines/$id',
    path: '/admin/machines/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/admin/customers/$id',
    path: '/admin/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/loyalty': typeof AuthenticatedAdminLoyaltyRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/customer/assignments': typeof AuthenticatedCustomerAssignmentsRoute
  '/customer/benefits': typeof AuthenticatedCustomerBenefitsRoute
  '/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/customer/loyalty': typeof AuthenticatedCustomerLoyaltyRoute
  '/customer/notifications': typeof AuthenticatedCustomerNotificationsRoute
  '/customer/profile': typeof AuthenticatedCustomerProfileRoute
  '/customer/requests': typeof AuthenticatedCustomerRequestsRoute
  '/insurance/approved': typeof AuthenticatedInsuranceApprovedRoute
  '/insurance/dashboard': typeof AuthenticatedInsuranceDashboardRoute
  '/insurance/notifications': typeof AuthenticatedInsuranceNotificationsRoute
  '/insurance/pending': typeof AuthenticatedInsurancePendingRoute
  '/insurance/profile': typeof AuthenticatedInsuranceProfileRoute
  '/insurance/rejected': typeof AuthenticatedInsuranceRejectedRoute
  '/operator/benefits': typeof AuthenticatedOperatorBenefitsRoute
  '/operator/dashboard': typeof AuthenticatedOperatorDashboardRoute
  '/operator/notifications': typeof AuthenticatedOperatorNotificationsRoute
  '/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/machines/$id': typeof AuthenticatedAdminMachinesIdRoute
  '/admin/operators/$id': typeof AuthenticatedAdminOperatorsIdRoute
  '/admin/service-requests/$id': typeof AuthenticatedAdminServiceRequestsIdRoute
  '/customer/machines/$id': typeof AuthenticatedCustomerMachinesIdRoute
  '/customer/operators/$id': typeof AuthenticatedCustomerOperatorsIdRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/machines/': typeof AuthenticatedAdminMachinesIndexRoute
  '/admin/operators/': typeof AuthenticatedAdminOperatorsIndexRoute
  '/admin/service-requests/': typeof AuthenticatedAdminServiceRequestsIndexRoute
  '/customer/machines/': typeof AuthenticatedCustomerMachinesIndexRoute
  '/customer/operators/': typeof AuthenticatedCustomerOperatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/loyalty': typeof AuthenticatedAdminLoyaltyRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/customer/assignments': typeof AuthenticatedCustomerAssignmentsRoute
  '/customer/benefits': typeof AuthenticatedCustomerBenefitsRoute
  '/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/customer/loyalty': typeof AuthenticatedCustomerLoyaltyRoute
  '/customer/notifications': typeof AuthenticatedCustomerNotificationsRoute
  '/customer/profile': typeof AuthenticatedCustomerProfileRoute
  '/customer/requests': typeof AuthenticatedCustomerRequestsRoute
  '/insurance/approved': typeof AuthenticatedInsuranceApprovedRoute
  '/insurance/dashboard': typeof AuthenticatedInsuranceDashboardRoute
  '/insurance/notifications': typeof AuthenticatedInsuranceNotificationsRoute
  '/insurance/pending': typeof AuthenticatedInsurancePendingRoute
  '/insurance/profile': typeof AuthenticatedInsuranceProfileRoute
  '/insurance/rejected': typeof AuthenticatedInsuranceRejectedRoute
  '/operator/benefits': typeof AuthenticatedOperatorBenefitsRoute
  '/operator/dashboard': typeof AuthenticatedOperatorDashboardRoute
  '/operator/notifications': typeof AuthenticatedOperatorNotificationsRoute
  '/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/machines/$id': typeof AuthenticatedAdminMachinesIdRoute
  '/admin/operators/$id': typeof AuthenticatedAdminOperatorsIdRoute
  '/admin/service-requests/$id': typeof AuthenticatedAdminServiceRequestsIdRoute
  '/customer/machines/$id': typeof AuthenticatedCustomerMachinesIdRoute
  '/customer/operators/$id': typeof AuthenticatedCustomerOperatorsIdRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/machines': typeof AuthenticatedAdminMachinesIndexRoute
  '/admin/operators': typeof AuthenticatedAdminOperatorsIndexRoute
  '/admin/service-requests': typeof AuthenticatedAdminServiceRequestsIndexRoute
  '/customer/machines': typeof AuthenticatedCustomerMachinesIndexRoute
  '/customer/operators': typeof AuthenticatedCustomerOperatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/loyalty': typeof AuthenticatedAdminLoyaltyRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/customer/assignments': typeof AuthenticatedCustomerAssignmentsRoute
  '/_authenticated/customer/benefits': typeof AuthenticatedCustomerBenefitsRoute
  '/_authenticated/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/_authenticated/customer/loyalty': typeof AuthenticatedCustomerLoyaltyRoute
  '/_authenticated/customer/notifications': typeof AuthenticatedCustomerNotificationsRoute
  '/_authenticated/customer/profile': typeof AuthenticatedCustomerProfileRoute
  '/_authenticated/customer/requests': typeof AuthenticatedCustomerRequestsRoute
  '/_authenticated/insurance/approved': typeof AuthenticatedInsuranceApprovedRoute
  '/_authenticated/insurance/dashboard': typeof AuthenticatedInsuranceDashboardRoute
  '/_authenticated/insurance/notifications': typeof AuthenticatedInsuranceNotificationsRoute
  '/_authenticated/insurance/pending': typeof AuthenticatedInsurancePendingRoute
  '/_authenticated/insurance/profile': typeof AuthenticatedInsuranceProfileRoute
  '/_authenticated/insurance/rejected': typeof AuthenticatedInsuranceRejectedRoute
  '/_authenticated/operator/benefits': typeof AuthenticatedOperatorBenefitsRoute
  '/_authenticated/operator/dashboard': typeof AuthenticatedOperatorDashboardRoute
  '/_authenticated/operator/notifications': typeof AuthenticatedOperatorNotificationsRoute
  '/_authenticated/operator/profile': typeof AuthenticatedOperatorProfileRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/machines/$id': typeof AuthenticatedAdminMachinesIdRoute
  '/_authenticated/admin/operators/$id': typeof AuthenticatedAdminOperatorsIdRoute
  '/_authenticated/admin/service-requests/$id': typeof AuthenticatedAdminServiceRequestsIdRoute
  '/_authenticated/customer/machines/$id': typeof AuthenticatedCustomerMachinesIdRoute
  '/_authenticated/customer/operators/$id': typeof AuthenticatedCustomerOperatorsIdRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/admin/machines/': typeof AuthenticatedAdminMachinesIndexRoute
  '/_authenticated/admin/operators/': typeof AuthenticatedAdminOperatorsIndexRoute
  '/_authenticated/admin/service-requests/': typeof AuthenticatedAdminServiceRequestsIndexRoute
  '/_authenticated/customer/machines/': typeof AuthenticatedCustomerMachinesIndexRoute
  '/_authenticated/customer/operators/': typeof AuthenticatedCustomerOperatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/assignments'
    | '/admin/benefits'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/notifications'
    | '/admin/settings'
    | '/customer/assignments'
    | '/customer/benefits'
    | '/customer/dashboard'
    | '/customer/loyalty'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/requests'
    | '/insurance/approved'
    | '/insurance/dashboard'
    | '/insurance/notifications'
    | '/insurance/pending'
    | '/insurance/profile'
    | '/insurance/rejected'
    | '/operator/benefits'
    | '/operator/dashboard'
    | '/operator/notifications'
    | '/operator/profile'
    | '/admin/customers/$id'
    | '/admin/machines/$id'
    | '/admin/operators/$id'
    | '/admin/service-requests/$id'
    | '/customer/machines/$id'
    | '/customer/operators/$id'
    | '/admin/customers/'
    | '/admin/machines/'
    | '/admin/operators/'
    | '/admin/service-requests/'
    | '/customer/machines/'
    | '/customer/operators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/assignments'
    | '/admin/benefits'
    | '/admin/dashboard'
    | '/admin/loyalty'
    | '/admin/notifications'
    | '/admin/settings'
    | '/customer/assignments'
    | '/customer/benefits'
    | '/customer/dashboard'
    | '/customer/loyalty'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/requests'
    | '/insurance/approved'
    | '/insurance/dashboard'
    | '/insurance/notifications'
    | '/insurance/pending'
    | '/insurance/profile'
    | '/insurance/rejected'
    | '/operator/benefits'
    | '/operator/dashboard'
    | '/operator/notifications'
    | '/operator/profile'
    | '/admin/customers/$id'
    | '/admin/machines/$id'
    | '/admin/operators/$id'
    | '/admin/service-requests/$id'
    | '/customer/machines/$id'
    | '/customer/operators/$id'
    | '/admin/customers'
    | '/admin/machines'
    | '/admin/operators'
    | '/admin/service-requests'
    | '/customer/machines'
    | '/customer/operators'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/benefits'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/loyalty'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/customer/assignments'
    | '/_authenticated/customer/benefits'
    | '/_authenticated/customer/dashboard'
    | '/_authenticated/customer/loyalty'
    | '/_authenticated/customer/notifications'
    | '/_authenticated/customer/profile'
    | '/_authenticated/customer/requests'
    | '/_authenticated/insurance/approved'
    | '/_authenticated/insurance/dashboard'
    | '/_authenticated/insurance/notifications'
    | '/_authenticated/insurance/pending'
    | '/_authenticated/insurance/profile'
    | '/_authenticated/insurance/rejected'
    | '/_authenticated/operator/benefits'
    | '/_authenticated/operator/dashboard'
    | '/_authenticated/operator/notifications'
    | '/_authenticated/operator/profile'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/machines/$id'
    | '/_authenticated/admin/operators/$id'
    | '/_authenticated/admin/service-requests/$id'
    | '/_authenticated/customer/machines/$id'
    | '/_authenticated/customer/operators/$id'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/admin/machines/'
    | '/_authenticated/admin/operators/'
    | '/_authenticated/admin/service-requests/'
    | '/_authenticated/customer/machines/'
    | '/_authenticated/customer/operators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator/profile': {
      id: '/_authenticated/operator/profile'
      path: '/operator/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof AuthenticatedOperatorProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operator/notifications': {
      id: '/_authenticated/operator/notifications'
      path: '/operator/notifications'
      fullPath: '/operator/notifications'
      preLoaderRoute: typeof AuthenticatedOperatorNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operator/dashboard': {
      id: '/_authenticated/operator/dashboard'
      path: '/operator/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof AuthenticatedOperatorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operator/benefits': {
      id: '/_authenticated/operator/benefits'
      path: '/operator/benefits'
      fullPath: '/operator/benefits'
      preLoaderRoute: typeof AuthenticatedOperatorBenefitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/rejected': {
      id: '/_authenticated/insurance/rejected'
      path: '/insurance/rejected'
      fullPath: '/insurance/rejected'
      preLoaderRoute: typeof AuthenticatedInsuranceRejectedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/profile': {
      id: '/_authenticated/insurance/profile'
      path: '/insurance/profile'
      fullPath: '/insurance/profile'
      preLoaderRoute: typeof AuthenticatedInsuranceProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/pending': {
      id: '/_authenticated/insurance/pending'
      path: '/insurance/pending'
      fullPath: '/insurance/pending'
      preLoaderRoute: typeof AuthenticatedInsurancePendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/notifications': {
      id: '/_authenticated/insurance/notifications'
      path: '/insurance/notifications'
      fullPath: '/insurance/notifications'
      preLoaderRoute: typeof AuthenticatedInsuranceNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/dashboard': {
      id: '/_authenticated/insurance/dashboard'
      path: '/insurance/dashboard'
      fullPath: '/insurance/dashboard'
      preLoaderRoute: typeof AuthenticatedInsuranceDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insurance/approved': {
      id: '/_authenticated/insurance/approved'
      path: '/insurance/approved'
      fullPath: '/insurance/approved'
      preLoaderRoute: typeof AuthenticatedInsuranceApprovedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/requests': {
      id: '/_authenticated/customer/requests'
      path: '/customer/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof AuthenticatedCustomerRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/profile': {
      id: '/_authenticated/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof AuthenticatedCustomerProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/notifications': {
      id: '/_authenticated/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof AuthenticatedCustomerNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/loyalty': {
      id: '/_authenticated/customer/loyalty'
      path: '/customer/loyalty'
      fullPath: '/customer/loyalty'
      preLoaderRoute: typeof AuthenticatedCustomerLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/dashboard': {
      id: '/_authenticated/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof AuthenticatedCustomerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/benefits': {
      id: '/_authenticated/customer/benefits'
      path: '/customer/benefits'
      fullPath: '/customer/benefits'
      preLoaderRoute: typeof AuthenticatedCustomerBenefitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/assignments': {
      id: '/_authenticated/customer/assignments'
      path: '/customer/assignments'
      fullPath: '/customer/assignments'
      preLoaderRoute: typeof AuthenticatedCustomerAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/loyalty': {
      id: '/_authenticated/admin/loyalty'
      path: '/admin/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AuthenticatedAdminLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/benefits': {
      id: '/_authenticated/admin/benefits'
      path: '/admin/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AuthenticatedAdminBenefitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/operators/': {
      id: '/_authenticated/customer/operators/'
      path: '/customer/operators'
      fullPath: '/customer/operators/'
      preLoaderRoute: typeof AuthenticatedCustomerOperatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/machines/': {
      id: '/_authenticated/customer/machines/'
      path: '/customer/machines'
      fullPath: '/customer/machines/'
      preLoaderRoute: typeof AuthenticatedCustomerMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/service-requests/': {
      id: '/_authenticated/admin/service-requests/'
      path: '/admin/service-requests'
      fullPath: '/admin/service-requests/'
      preLoaderRoute: typeof AuthenticatedAdminServiceRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/operators/': {
      id: '/_authenticated/admin/operators/'
      path: '/admin/operators'
      fullPath: '/admin/operators/'
      preLoaderRoute: typeof AuthenticatedAdminOperatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/machines/': {
      id: '/_authenticated/admin/machines/'
      path: '/admin/machines'
      fullPath: '/admin/machines/'
      preLoaderRoute: typeof AuthenticatedAdminMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/operators/$id': {
      id: '/_authenticated/customer/operators/$id'
      path: '/customer/operators/$id'
      fullPath: '/customer/operators/$id'
      preLoaderRoute: typeof AuthenticatedCustomerOperatorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer/machines/$id': {
      id: '/_authenticated/customer/machines/$id'
      path: '/customer/machines/$id'
      fullPath: '/customer/machines/$id'
      preLoaderRoute: typeof AuthenticatedCustomerMachinesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/service-requests/$id': {
      id: '/_authenticated/admin/service-requests/$id'
      path: '/admin/service-requests/$id'
      fullPath: '/admin/service-requests/$id'
      preLoaderRoute: typeof AuthenticatedAdminServiceRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/operators/$id': {
      id: '/_authenticated/admin/operators/$id'
      path: '/admin/operators/$id'
      fullPath: '/admin/operators/$id'
      preLoaderRoute: typeof AuthenticatedAdminOperatorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/machines/$id': {
      id: '/_authenticated/admin/machines/$id'
      path: '/admin/machines/$id'
      fullPath: '/admin/machines/$id'
      preLoaderRoute: typeof AuthenticatedAdminMachinesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/admin/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminBenefitsRoute: typeof AuthenticatedAdminBenefitsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminLoyaltyRoute: typeof AuthenticatedAdminLoyaltyRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedCustomerAssignmentsRoute: typeof AuthenticatedCustomerAssignmentsRoute
  AuthenticatedCustomerBenefitsRoute: typeof AuthenticatedCustomerBenefitsRoute
  AuthenticatedCustomerDashboardRoute: typeof AuthenticatedCustomerDashboardRoute
  AuthenticatedCustomerLoyaltyRoute: typeof AuthenticatedCustomerLoyaltyRoute
  AuthenticatedCustomerNotificationsRoute: typeof AuthenticatedCustomerNotificationsRoute
  AuthenticatedCustomerProfileRoute: typeof AuthenticatedCustomerProfileRoute
  AuthenticatedCustomerRequestsRoute: typeof AuthenticatedCustomerRequestsRoute
  AuthenticatedInsuranceApprovedRoute: typeof AuthenticatedInsuranceApprovedRoute
  AuthenticatedInsuranceDashboardRoute: typeof AuthenticatedInsuranceDashboardRoute
  AuthenticatedInsuranceNotificationsRoute: typeof AuthenticatedInsuranceNotificationsRoute
  AuthenticatedInsurancePendingRoute: typeof AuthenticatedInsurancePendingRoute
  AuthenticatedInsuranceProfileRoute: typeof AuthenticatedInsuranceProfileRoute
  AuthenticatedInsuranceRejectedRoute: typeof AuthenticatedInsuranceRejectedRoute
  AuthenticatedOperatorBenefitsRoute: typeof AuthenticatedOperatorBenefitsRoute
  AuthenticatedOperatorDashboardRoute: typeof AuthenticatedOperatorDashboardRoute
  AuthenticatedOperatorNotificationsRoute: typeof AuthenticatedOperatorNotificationsRoute
  AuthenticatedOperatorProfileRoute: typeof AuthenticatedOperatorProfileRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminMachinesIdRoute: typeof AuthenticatedAdminMachinesIdRoute
  AuthenticatedAdminOperatorsIdRoute: typeof AuthenticatedAdminOperatorsIdRoute
  AuthenticatedAdminServiceRequestsIdRoute: typeof AuthenticatedAdminServiceRequestsIdRoute
  AuthenticatedCustomerMachinesIdRoute: typeof AuthenticatedCustomerMachinesIdRoute
  AuthenticatedCustomerOperatorsIdRoute: typeof AuthenticatedCustomerOperatorsIdRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
  AuthenticatedAdminMachinesIndexRoute: typeof AuthenticatedAdminMachinesIndexRoute
  AuthenticatedAdminOperatorsIndexRoute: typeof AuthenticatedAdminOperatorsIndexRoute
  AuthenticatedAdminServiceRequestsIndexRoute: typeof AuthenticatedAdminServiceRequestsIndexRoute
  AuthenticatedCustomerMachinesIndexRoute: typeof AuthenticatedCustomerMachinesIndexRoute
  AuthenticatedCustomerOperatorsIndexRoute: typeof AuthenticatedCustomerOperatorsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
  AuthenticatedAdminBenefitsRoute: AuthenticatedAdminBenefitsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminLoyaltyRoute: AuthenticatedAdminLoyaltyRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedCustomerAssignmentsRoute: AuthenticatedCustomerAssignmentsRoute,
  AuthenticatedCustomerBenefitsRoute: AuthenticatedCustomerBenefitsRoute,
  AuthenticatedCustomerDashboardRoute: AuthenticatedCustomerDashboardRoute,
  AuthenticatedCustomerLoyaltyRoute: AuthenticatedCustomerLoyaltyRoute,
  AuthenticatedCustomerNotificationsRoute:
    AuthenticatedCustomerNotificationsRoute,
  AuthenticatedCustomerProfileRoute: AuthenticatedCustomerProfileRoute,
  AuthenticatedCustomerRequestsRoute: AuthenticatedCustomerRequestsRoute,
  AuthenticatedInsuranceApprovedRoute: AuthenticatedInsuranceApprovedRoute,
  AuthenticatedInsuranceDashboardRoute: AuthenticatedInsuranceDashboardRoute,
  AuthenticatedInsuranceNotificationsRoute:
    AuthenticatedInsuranceNotificationsRoute,
  AuthenticatedInsurancePendingRoute: AuthenticatedInsurancePendingRoute,
  AuthenticatedInsuranceProfileRoute: AuthenticatedInsuranceProfileRoute,
  AuthenticatedInsuranceRejectedRoute: AuthenticatedInsuranceRejectedRoute,
  AuthenticatedOperatorBenefitsRoute: AuthenticatedOperatorBenefitsRoute,
  AuthenticatedOperatorDashboardRoute: AuthenticatedOperatorDashboardRoute,
  AuthenticatedOperatorNotificationsRoute:
    AuthenticatedOperatorNotificationsRoute,
  AuthenticatedOperatorProfileRoute: AuthenticatedOperatorProfileRoute,
  AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  AuthenticatedAdminMachinesIdRoute: AuthenticatedAdminMachinesIdRoute,
  AuthenticatedAdminOperatorsIdRoute: AuthenticatedAdminOperatorsIdRoute,
  AuthenticatedAdminServiceRequestsIdRoute:
    AuthenticatedAdminServiceRequestsIdRoute,
  AuthenticatedCustomerMachinesIdRoute: AuthenticatedCustomerMachinesIdRoute,
  AuthenticatedCustomerOperatorsIdRoute: AuthenticatedCustomerOperatorsIdRoute,
  AuthenticatedAdminCustomersIndexRoute: AuthenticatedAdminCustomersIndexRoute,
  AuthenticatedAdminMachinesIndexRoute: AuthenticatedAdminMachinesIndexRoute,
  AuthenticatedAdminOperatorsIndexRoute: AuthenticatedAdminOperatorsIndexRoute,
  AuthenticatedAdminServiceRequestsIndexRoute:
    AuthenticatedAdminServiceRequestsIndexRoute,
  AuthenticatedCustomerMachinesIndexRoute:
    AuthenticatedCustomerMachinesIndexRoute,
  AuthenticatedCustomerOperatorsIndexRoute:
    AuthenticatedCustomerOperatorsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
